version: "3.3"
services:
  worktime:
    build: .
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail -s http://localhost/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
